name: Daily BraTS Data Access Check

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cron/requirements.txt

      - name: Create Synapse config file
        env:
          SYNAPSE_USERNAME: ${{ secrets.SYNAPSE_USERNAME }}
          SYNAPSE_PAT: ${{ secrets.SYNAPSE_PAT }}
        run: |
          echo "[authentication]" > ~/.synapseConfig
          echo "username = $SYNAPSE_USERNAME" >> ~/.synapseConfig
          echo "authtoken = $SYNAPSE_PAT" >> ~/.synapseConfig

      - name: Run the Python script
        run: |
          python cron/invite_valid_response.py
